Add line width to planar line renderer
sebcrozet/kiss3d pull request #301
Opened 2022-07-08 02:21 UTC by RaduBerinde

The planar line renderer does not currently set the line width; when
rendering, it inherits any line width that was set by the 3D line
renderer (if it happened to be used).

This commit adds a line width setting to the planar line renderer; the
`window::set_line_width` method sets it together with the 3D line
width.

2022-07-08 02:35 UTC, RaduBerinde commented
Perhaps it would be better to have a separate `set_planar_line_width`?

In any case, it's unfortunate that all lines have to have the same width.

2022-07-13 17:07 UTC, RaduBerinde commented
CC @donkeyteethUX

2022-07-14 23:33 UTC, donkeyteethUX requested changes
Great, thanks. Just a small request.

2022-07-14 23:33 UTC, donkeyteethUX commented on src/planar_line_renderer.rs
> +    pub fn set_line_width(&mut self, line_width: f32) {
Can we assert strictly positive `line_width` (and document that) to avoid a cryptic panic downstream?

2022-07-15 21:27 UTC, merged